spring.application.name=projeto-fera

spring.datasource.url=jdbc:postgresql://localhost:5432/FeraMetalurgica

spring.datasource.username=postgres
spring.datasource.password=bear5503

spring.datasource.driverClassName=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate

